// auth actions
export const REQUEST_TOKEN = 'REQUEST_TOKEN'
export const RECEIVE_TOKEN = 'RECEIVE_TOKEN'
export const LOG_OUT = 'LOG_OUT'
export const RELOAD_AVATAR = 'RELOAD_AVATAR'

// user actions
export const RECEIVE_USER_INFO = 'RECEIVE_USER_INFO'

// status actions
export const SET_STATUS = 'SET_STATUS'
export const SET_WORK  = 'SET_WORK'
export const DONE_WORK = 'DONE_WORK'
export const PUSH_ALERT = 'PUSH_ALERT'
export const CLOSE_ALERT = 'CLOSE_ALERT'

// news feed actions
export const SEND_POST = 'SEND_POST'
export const REQUEST_POST = 'REQUEST_POST'
export const RECEIVE_POST = 'RECEIVE_POST'
export const REQUEST_SEND_COMMENT = 'REQUEST_SEND_COMMENT'
export const RECEIVE_COMMENT = 'RECEIVE_COMMENT'

// members actions
export const REQUEST_MEMBERS = 'RECEIVE_MEMBERS'
export const RECEIVE_MEMBERS = 'RECEIVE_MEMBERS'
export const REQUEST_ALL_MEMBERS = 'RECEIVE_ALL_MEMBERS'
export const RECEIVE_ALL_MEMBERS = 'RECEIVE_ALL_MEMBERS'

// chat actions
export const RECEIVE_CHAT_HISTORY = 'RECEIVE_CHAT_HISTORY'
export const SEND_CHAT_MESSAGE = 'SEND_CHAT_MESSAGE'
export const RECEIVE_CHAT_MESSAGE = 'RECEIVE_CHAT_MESSAGE'
export const SHOW_CHAT = 'SHOW_CHAT'
export const HIDE_CHAT = 'HIDE_CHAT'
export const MINUS_CHAT = 'MINUS_CHAT'
export const RECEIVE_UNREADED = 'RECEIVE_UNREADED'
export const RECEIVE_RECENTS_CHAT = 'RECEIVE_RECENTS_CHAT'

// test actions
export const REQUEST_TEST = 'REQUEST_TEST'
export const RECEIVE_TEST = 'RECEIVE_TEST'
export const REQUEST_QUESTION = 'REQUEST_QUESTION'
export const RECEIVE_QUESTION = 'RECEIVE_QUESTION'
export const TEST_TIME_OUT = 'TEST_TIME_OUT'
export const SEND_ANSWER = 'SEND_ANSWER'
export const RECEIVE_RESULT = 'RECEIVE_RESULT'
export const TEST_FINISHED = 'TEST_FINISHED'
export const REQUEST_TEST_STATUS = 'REQUEST_TEST_STATUS'
export const RECEIVE_TEST_STATUS = 'RECEIVE_TEST_STATUS'
export const POST_QUESTION = 'POST_QUESTION'
export const RECEIVE_POST_QUESTION_RESULT = 'RECEIVE_POST_QUESTION_RESULT'
export const REQUEST_QUESTIONS = 'REQUEST_QUESTIONS'
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS'
export const POST_TEST = 'POST_TEST'
export const RECEIVE_POST_TEST_RESULT = 'RECEIVE_POST_TEST_RESULT'

// test detail
export const REQUEST_TEST_DETAIL = 'REQUEST_TEST_DETAIL'
export const RECEIVE_TEST_DETAIL = 'RECEIVE_TEST_DETAIL'

// test history
export const REQUEST_HISTORY = 'REQUEST_HISTORY'
export const RECEIVE_HISTORY = 'RECEIVE_HISTORY'
